# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jean-Christophe Baptiste
title: Expert indépendant en cyber sécurité
email: contact@jcbaptiste.com
website: jcbaptiste.com

# SEO
tagline: Présentation de Jean-Christophe Baptiste, expert indépendant en cybersécurité
description: |
  Devis sur demande pour toute expertise, conseil, audit en cyber sécurité : investigation numérique (digital forensics), test d'intrusion (penetration testing), audit d'architecture, système, réseau, web, analyse de risque EBIOS/ISO27005, PCI-DSS.
locale: fr_FR
author: Jean-Christophe Baptiste
twitter:
  username: _phocean
  card: summary
url: https://jcbaptiste.com
logo: /images/profile.jpg
social:
  name: phocean
  links:
    - https://twitter.com/_phocean
    - https://www.linkedin.com/in/jcbaptiste/
    - https://github.com/phocean
    - https://keybase.io/phocean

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: _phocean
github_username:  phocean
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jcbaptiste
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: keybase.io
  icon: fa fa-key
  url: https://keybase.io/phocean
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "G-623RT5W745"

# About Section
about_title: À propos
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour,

  Je développe mon expertise dans le domaine de la <mark>cyber sécurité</mark> depuis 20 ans.

  Mon expérience s'est bâtie sur une première orientation dans l'architecture réseau et l'intégration de systèmes d'exploitation Linux. Mes activités professionnelles m'ont ensuite permis de me spécialiser dans la sécurité de l'information, tant sur les aspects défensifs qu'offensifs.

  J'exerce à ce titre depuis de nombreuses années comme <mark>consultant</mark> senior, <mark>auditeur</mark> et <mark>formateur</mark>. J'ai également eu l'opportunité d'encadrer des équipes d'experts en tant que responsable, ainsi que de traiter des questions commerciales, stratégiques et budgétaires en tant que directeur d'une offre de conseil spécialisée et qualifiée PASSI par l'ANSSI sur l'ensemble des portées techniques.

  Désormais **expert indépendant**, je vous propose mon savoir-faire au travers des prestations suivantes :
  - <mark>Investigation numérique</mark> (*digital forensics*) ;
  - <mark>Test d'intrusion</mark> (*pentest*) Web, infrastructure et sans-fil ;
  - <mark>Test de robustesse</mark> et <mark>audit de configuration</mark> système ;
  - <mark>Analyse de risque</mark> (EBIOS, ISO27005) ;
  - Conseil en <mark>architecture</mark> système et réseau, ou sur mesure ;
  - Préparation à la qualification <mark>PASSI</mark> ou à la certification <mark>PCI-DSS</mark> ;
  - <mark>Formation</mark> (administrateurs, développeurs) ;
  - <mark>Sensibilisation</mark> (tous publics).
  
  Pour tout renseignement complémentaire, conseil ou devis, contactez-moi par [courriel](mailto:contact@jcbaptiste.com) ou par un des réseaux sociaux en en-tête de cette page. Je m'engage à vous répondre avec la réactivité et la rigueur que nécessite votre intérêt.

content:

  - title: Certifications
    layout: text
    content: |
        <mark>CISSP</mark> #423905 - <mark>ISO 27005</mark> risk manager - Analyste <mark>EBIOS</mark> (PECB) - <mark>CEH</mark> (EC-Council) - <mark>CHFI</mark> (EC-Council) - ex-<mark>PCI QSA</mark> (PCI SSC) - ex-qualifié <mark>PASSI</mark>

  - title: Principales Expériences # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: TNP consultants
        link: tnpitsecurity.com
        # link_text: boringcompany.com
        sub_title: Directeur
        caption: Avril 2021 - Novembre 2022
        quote: >
          Création et développement d'une offre cyber sécurité qualifiée PASSI
        description: | # this will include new lines to allow paragraphs
          - Définition de la **stratégie commerciale** et des **objectifs financiers** sur 3 ans ;
          - **Recrutement** : 8 collaborateurs, commerciaux, responsables et experts techniques ;
          - **Prospection**, suivi commercial, réponses aux appels d'offre ;
          - Arbitrage technique et organisationnel, participation aux **comités de direction** ;
          - Pilotage de la **qualification PASSI** débutée en septembre 2022 et obtenue en décembre 2022, **toutes portées** : test d'intrusion, audit d'architecture, audit de configuration, audit de code source, audit organisationnel et physique.
          - **Formateur** en hacking éthique et investigation numérique
          - **Auditeur qualifié PASSI** : responsable d'audit, test d'intrusion, audit d'architecture, audit de configuration, audit organisationnel et physique.
      
      - layout: left
        title: Sysdream
        link: sysdream.com
        sub_title: Responsable Audit, R&D - Consultant et Formateur
        caption: Février 2014 - Février 2022
        quote: >
          Encadrement, audit, formation et recherche au service d'un acteur spécialiste de la cyber sécurité offensive
        description: |
          - **Responsable de l'équipe d'audit** : suivi opérationnel des consultants (< 20 personnes) et des missions, recrutement, qualité, avant-vente.
          - **Responsable R&D** : organisation et pilotage des activités de recherche, contrôle et validation des publications, mise en place d'un programme de *bug bounty*, sélection des conférences pour l'événement *Hack in Paris*.
          - **Consultant** : tests d'intrusion (Web, infrastructure, sans-fil), audit d'architecture, audit de configuration, test de robustesse, investigation numérique, analyse de risque, audit de conformité PCI-DSS (auditeur PCI QSA).
          - **Auteur** de formations : Hacking Éthique (niveaux avancé et expert), radio et technologies sans-fil, investigation numérique, SIEM et systèmes de détection, introduction à l'analyse de malwares, Metasploit avancé, sensibilisation.
          - **Formateur** : CEH, CHFI (EC-Council); analyse de risque EBIOS et ISO27005 (PECB).
      
      - layout: left
        title: Air Liquide
        link : www.airliquide.com
        sub_title: Security Officer
        caption: Juin 2008 - Juin 2013
        quote: >
          Responsable et expert en sécurité des systèmes d'information industriels
        description: |
          - **Responsable de l'équipe sécurité** pour la production industrielle : suivi opérationnel des experts (3 personnes), écriture de la politique de sécurité, pilotage des projets défensifs, intégration dans le processus qualité.
          - **Expert et référent sécurité** : analyse de risque sur les projets du métier et les chantiers d'infrastructure, test d'intrusion, investigation numérique, veille technologique sur les composants du système d'information, rédaction d'appels d'offres et de cahiers des charges.
          - **Expert réseau** : conception de l'architecture cible et migration du centre d'hébergement, dans un contexte de continuité de service 24/7 : redondance réseau, opérations complexes de routage et d'équilibrage de charge, bascules progressives des actifs du métier.
          - **Recherche** : recherches de vulnérabilités et publications sur des équipements industriels (SCADA, MOXA).
        
        
  - title: Éducation # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ingénieur ESGI
        caption: 1999 - 2004
        sub_title: Paris
        description: École Supérieure de Génie Informatique, spécialité Réseau et Télécommunication

  - title: Ateliers
    layout: text
    content: |
        - **Practical IoT hacking** (Hack in Paris, 2019)
        - **Intelligence artificielle** - Machine Learning** (Human Coders, 2019)
        - **Smart Lock Picking** (Hack in Paris, 2018)
        - **Practical SAP Netweaver ABAP pentest** (Hack in Paris, 2017)
        - **Pentesting ICS** (Hack in Paris, 2016)
        - **FOR526 - Memory Analysis in-depth** (SANS, 2015)
        - **Malware Reversing** (Hack in Paris, 2011)
  
  - title: Langues
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <mark>Français</mark> : langue maternelle ;
      - <mark>Anglais</mark> : lu, écrit, parlé avec aisance - niveau avancé (TOEIC 950) ;
      - <mark>Japonais</mark> : niveau élémentaire.
        
  - title: Autres occupations
    layout: text
    content: | # this will include new lines to allow paragraphs
      En dehors de la technologie, je privilégie les activités physiques et de plein air, notamment :
      - le <mark>sport</mark> ;
      - la <mark>photographie</mark>.

# Footer
footer_show_references: true
references_title: Devis sur demande - SIRET 79759543600016

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
